FROM rocker/shiny-verse:4.0.3
MAINTAINER "Andrew Barker" andbarker@gmail.com

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    lbzip2 \
    libfftw3-dev \
    libgdal-dev \
    libgeos-dev \
    libgsl0-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libhdf4-alt-dev \
    libhdf5-dev \
    libjq-dev \
    liblwgeom-dev \
    libpq-dev \
    libproj-dev \
    libprotobuf-dev \
    libnetcdf-dev \
    libsqlite3-dev \
    libssl-dev \
    libudunits2-dev \
    netcdf-bin \
    postgis \
    protobuf-compiler \
    sqlite3 \
    tk-dev \
    unixodbc-dev \
  && install2.r --error \
    bs4Dash \
    bslib \
    cowplot \
    DBI \
    DT \
    RColorBrewer \
    RandomFields \
    RNetCDF \
    classInt \
    data.table \
    deldir \
    devtools \
    dbplyr \ 
    dplyr \
    dtplyr \
    expint \
    flextable \
    gdalUtils \
    ggplot2 \
    gstat \
    hdf5r \
    kableExtra \
    leaflet \
    leaflet.extras \
    lidR \
    lintr \
    lubridate \
    lwgeom \
    magrittr \
    mapdata \
    mapdeck \
    mapedit \
    maptools \
    mapview \
    metR \
    ncdf4 \
    odbc \
    officer \
    openxlsx \
    pkgdown \
    patchwork \
    plotly \
    proj4 \
    raster \
    rbokeh \
    RColorBrewer \
    readr \
    readxl \
    rgdal \
    rgeos \
    rhandsontable \
    rlas \
    rmarkdown \
    RSQLite \
    RPostgres \
    rvest \ 
    scales \
    sf \
    shiny \
    shinyalert \
    shinycssloaders \
    shinydashboard \
    shinyjs \
    shinythemes \
    shinyWidgets \
    sp \
    spacetime \
    spatstat \
    spatialreg \
    spdep \
    stars \
    stringr \
    tibble \
    tidyr \
	  tmap \
	  units \
	  webshot \ 
    geoR \
    geosphere \
    ## from bioconductor
    && R -e "BiocManager::install('rhdf5')" \
    && R -e "devtools::install_github('nik01010/dashboardthemes')" \
    && R -e "devtools::install_github('dreamRs/shinyWidgets')" \
    && R -e "devtools::install_github('daattali/shinycssloaders')"
